Repository Electric-Coin-Company/zashi-android, pull requests merged in 2023-07, with the labels that each got.

#703 [#664] Transaction History List
  docs/testing/manual_testing/TransactionHistory.md
  gradle.properties
  ui-design-lib/src/main/java/co/electriccoin/zcash/ui/design/component/Text.kt
  ui-lib/build.gradle.kts
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/common/FlowExtTest.kt
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/history/HistoryTestSetup.kt
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/history/fixture/TransactionHistorySyncStateFixture.kt
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/history/view/HistoryViewTest.kt
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/HomeTestSetup.kt
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/home/view/HomeViewTest.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/Navigation.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/AndroidHistory.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/HistoryTag.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/state/TransactionHistorySyncState.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/history/view/HistoryView.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/AndroidHome.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/model/WalletSnapshot.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/view/HomeView.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/home/viewmodel/WalletViewModel.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/onboarding/AndroidOnboarding.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/request/view/RequestView.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/support/model/TimeInfo.kt
  ui-lib/src/main/res/ui/history/values/strings.xml
  ui-lib/src/main/res/ui/home/values/strings.xml
  ui-screenshot-test/src/main/java/co/electroniccoin/zcash/ui/screenshot/ScreenshotTest.kt
Labels: enhancement, tech-debt

#899 [#898] Adopt Bip39 1.0.5
  gradle.properties
Labels: dependencies, tech-debt

#900 [#897] Fix failing keyboard_disappears_after_seed
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/receive/view/ReceiveViewTest.kt
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/restore/view/RestoreViewAndroidTest.kt
Labels: bug

#906 [#905] Add copy-to-clipboard for addresses
  spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/ClipboardManagerExt.kt
  spackle-android-lib/src/main/kotlin/co/electriccoin/zcash/spackle/ClipboardManagerUtil.kt
  ui-lib/src/androidTest/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressViewTest.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/AndroidWalletAddresses.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/WalletAddressesTag.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/address/view/WalletAddressView.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/backup/AndroidBackup.kt
  ui-lib/src/main/java/co/electriccoin/zcash/ui/screen/seed/AndroidSeed.kt
  ui-lib/src/main/res/ui/wallet_address/values/strings.xml
Labels: enhancement

#910 [#903] Update doc on supported java versions
  docs/Setup.md
  gradle.properties
Labels: documentation
